
  library(tidyverse)
  library(jagsUI)

  remove(list = ls())
  unlogit <- function(x) exp(x) / (1 + exp(x))

# load data and N estimates generated by "Harvest Rolling Mice data recapture.R"
  load("data/N estimates.RData")

# view trapping nights file  
  glimpse(tn)

####################################################################################
# for each grid, get the population size per trip
  size <- function(grid) {
    out <- apply(N[, , grid], 2, function(x) quantile(x, c(0.025, 0.5, 0.975), na.rm = T))
    out <- data.frame(t(out))
    names(out) <- c("lcl", "med", "ucl")
    out$grid <- grid
    out$trip <- 1:5
    return(out)
  }
  
  Nout <- size(1)
  for(i in 2:6) {
    Nout <- rbind(Nout, size(i))
  }
  
  Nout <- full_join(all, Nout)

  min.mice <- min.mice %>%
    arrange(grid, trip)
  
  Nout <- full_join(Nout, min.mice)
  Nout
  
  ggplot(Nout, aes(y = med, x = trip)) +
    geom_point(size = 3) +
    geom_line() +
    geom_errorbar(aes(ymin = lcl, ymax = ucl), width = 0.2) +
    facet_wrap(~ DataSiteName) +
    ylab("Mark-recapture estimate of population size") +
    xlab("Trip") +
    theme_bw()
  
